# Generated by Django 4.0.6 on 2024-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nome',
            new_name='name',
        ),
    ]
